name: Docker build
on:
  push:
    branches:
      - docker-builds
jobs:
  build-docker-image:
    strategy:
      matrix:
        freecad_tag: [1.0.0, 0.21.2]
      fail-fast: false
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        #        if: github.ref == 'refs/heads/publish'
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: toastedcrumpets/freecad-action:${{  matrix.freecad_tag }}
          build-args: |
            FREECAD_TAG=${{  matrix.freecad_tag }}
